
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "My Portfolio - Website",
  description: "Generated by me to store my personal info",
   icons: {
    icon: "/portfolio.png",
  },
};

export default function RootLayout({ children }) {

  
  


  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >


        <Navbar/>
        {children}
      </body>
    </html>
  );
}
